import '@douyinfe/semi-ui-19/dist/css/semi.css'; // 👈 加在这里
import type { Metadata } from "next";

import "./globals.css";

 
export const metadata: Metadata = {
 title: "WMS 智能仓储系统",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
