import "@douyinfe/semi-ui-19/dist/css/semi.css"; // 👈 加在这里
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "WMS 智能仓储系统",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // 定义变量名
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.variable}`}>{children}</body>
    </html>
  );
}
